const TRIP_CREATED = 1;
const TRIP_UPDATED = 2;
const TRIP_COMMENTED = 3;
const TRIP_APPROVED = 4;
const TRIP_REJECTED = 5;
const TRIP_ASSIGNED = 6;
const COMMENT_UPDATED = 7;

export default {
    TRIP_CREATED,
    TRIP_UPDATED,
    TRIP_COMMENTED,
    TRIP_APPROVED,
    TRIP_REJECTED,
    TRIP_ASSIGNED,
    COMMENT_UPDATED
};
